const esbuild = require('esbuild');
const fs = require('node:fs');
const path = require('node:path');

async function build() {
  const result = await esbuild.build({
    entryPoints: ['src/editor/xml-editor.js'],
    outfile: 'src/editor/xml-editor.bundle.js',
    bundle: true,
    format: 'esm',
    target: 'es2020',
    minify: true,
    metafile: true,
    banner: { js: '// Generated by npm run build:editor. Third-party licenses: LICENSES.txt.' },
  });
  const packages = new Map();
  for (const input of Object.keys(result.metafile.inputs)) {
    if (!input.startsWith('node_modules/')) continue;
    let directory = path.dirname(path.resolve(input));
    while (!fs.existsSync(path.join(directory, 'package.json'))) directory = path.dirname(directory);
    const pkg = JSON.parse(fs.readFileSync(path.join(directory, 'package.json'), 'utf8'));
    if (packages.has(pkg.name)) continue;
    const license = ['LICENSE', 'LICENSE.txt', 'LICENSE.md'].find((name) => fs.existsSync(path.join(directory, name)));
    if (!license) throw new Error(`License missing for ${pkg.name}`);
    packages.set(pkg.name, `${pkg.name} ${pkg.version}\n${fs.readFileSync(path.join(directory, license), 'utf8').trim()}`);
  }
  const notices = [...packages.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([, text]) => text);
  fs.writeFileSync('src/editor/LICENSES.txt', `${notices.join('\n\n-----\n\n')}\n`);
  console.log('Editor bundle and third-party licenses generated.');
}

build().catch((error) => { console.error(error); process.exitCode = 1; });
